services:

  ollama:
    profiles: [container]
    image: ollama/ollama:0.1.48
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - 11434:11434

  download-llm:
    profiles: [container]
    #image: curlimages/curl:8.6.0 this image does not work on Gitpod
    image: rancher/curlimages-curl:7.73.0
    entrypoint: ["curl", "ollama:11434/api/pull", "-d", "{\"name\": \"${LLM}\"}"]
    depends_on:
      ollama:
        condition: service_started

  my-app:
    #container_name: my-go-app
    profiles: [container, app]
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - LLM=${LLM}
      # host.docker.internal: listening the host from the container
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  ollama-data:
